### ISSUE TITLE
Refactor driveteam controls

### ISSUE THREAD

**Issue by natesales** [flamingchickens1540/toothless#63]
Open issue for discussion: what buttons should we have and where?

Driver:
- [x] Left/right sticks: tank drive
- [x] Left/right trigger: throttles
- [x] Left bumper hold: shoot

Copilot:
- [x] Left/right sticks: climber extension
- [x] D pad up/down: climber solenoids
- [x] A: "Acquire ball" (fold down and spin intake, start indexer)
- [x] B: Outtake
- [x] #42 
    - [x] Y: Eject only top ball through shooter
    - [x] X: Eject only bottom ball through intake

**Comment by sanashah007** [comment]
For the X can't I just outtake?

**Comment by rutmanz** [comment]
No, we may want to remove the bottom ball only, not the top ball. Reverse-intaking will get rid of both
