### ISSUE TITLE
Limelight pose usage with check at end of turn

### ISSUE THREAD

**Issue by knightss27** [flamingchickens1540/toothless#70]

**Comment by rutmanz** [comment]
@knightss27 Can you elaborate on what you mean by this?

**Comment by knightss27** [comment]
> @knightss27 Can you elaborate on what you mean by this?

The limelight should take a reading when the pointToTarget command is first called, and then it should attempt to move the number of degrees using only the navX as reference, checking to see if it is lined up at the end. This way we aren't continuously relying on limelight vision so if someone moves in front of us while turning we still end up able to make the shot.
